# throws

```shell
package Chapter08;

public class ExceptionTest5 {


		public static void main(String[] args) {
			try {
				testMethod(9, 0);
			} catch (Exception e) {

				System.out.println("0으로 나눌 수는 없어요.");
			}
			
			
		}

		private static void testMethod(int i, int j) throws ArithmeticException {
			//testMehod의 로직을 짜기도 바빠죽겠는데 예외처리까지 신경써줘야 하는 경우 throws를 통해 나를 호출한 쪽으로 부담을 넘긴다. 
			
			
			System.out.println("두 수의 나누기 결과 : " + (i/j));
		}

}
```

# throw

```shell

package Chapter08;

public class ExceptionTest6 {

	public static void main(String[] args) {
		try {
			int javaScore = Integer.parseInt(args[0]);

			if(javaScore < 0) {
				throw new IllegalArgumentException();
				// 하나의 예외객체를 강제로 발생시킬때 사용
			}

			System.out.println("계좌 이체 실행");
		} catch (IllegalArgumentException e) {
			System.out.println("음수는 처리 할 수가 없습니다.");

		}
	}


}
```
